### PR TITLE
Show vector tile labels on top of the path layer

### PR DESCRIPTION
**Pull request by easbar**
See #109

The Mapbox style consists of many layers with different types. Layers with type 'symbol' should be shown on top of all other layers including our route path layer. Otherwise street labels etc. will be hidden or hard to read. Mapbox offers a 'beforeId' option that allows specifying the position of custom map layers. So basically all we need to do is setting `beforeId` to the first symbol layer of the currently used map style. The main issue with this is that so far we only pass the url of the map style file to Mapbox which is then loaded by Mapbox internally. Therefore we cannot easily figure out which one is the first symbol layer.

In this PR I therefore:

* load all (three to be exact) Mapbox styles when the app starts and keep them in `MapOptionsStore`
* extract the first symbol layer from the loaded style
* use the id of this layer as `beforeId` when creating the paths layer

I think keeping the Mapbox style in `MapOptionsStore` is fine (I actually think it is better) rather than trying to 'hide' Mapbox related stuff from our state store. Just the fact alone that we are dealing with urls pointing to *Mapbox* styles is Mapbox specific anyway. This way we also get rid of the workaround introduced for #122 and there is no need to deal with things like `url: string | string[]` where `url` could be pointing to a mapbox style or might be a list of tile urls.

Loading the style files eagerly when the app starts is just one way this can be done. We could also do this lazily or every time the map style changes (like we currently do), but it is quite fast anyway, and pretty much negligible compared to the loading times for the different tiles:

image

todo: 

* [ ] currently there are some ugly errors in the console like this: (I don't really understand why)
```
// `water_name_line` is the first symbol layer
mapbox.js:30 Error: Layer with id "water_name_line" does not exist on this map.
```
   ~~Probably related to this: The labels are hidden until we change the map layer for the first time~~ (fixed)
* [ ] Are there any downsides? Does it make sense to fetch the mapbox style manually? Or should we even include it in the bundle?
* [ ] Reducing the opacity of the path layer might still be necessary:
image

### CODE REVIEW

**Comment by easbar** [comment]
> Layer with id "water_name_line" does not exist on this map.

I think this happens because we set the `beforeId` of e.g. the paths layer to `water_name_line` before the background layer has finished loading. So maybe we need to wait for something like Mapbox's `styledata` event and set the `beforeId` only afterwards.

**Comment by Janekdererste** [comment]
> So maybe we need to wait for something like Mapbox's styledata event and set the beforeId only afterwards

At least when the style is changed with a url one has to wait for the styledata callback anyway. Does it cause problems to set the bofereId at this point? When prefetching the styles. This callback should be called pretty much emediately?

**Comment by Janekdererste** [comment]
> The labels are hidden until we change the map layer for the first time

Do you know why?

**Comment by easbar** [comment]
> Do you know why?

This was just an error on my side and I already fixed it here: https://github.com/graphhopper/graphhopper-maps/pull/126/commits/e92640892162aa11c824f93f781cf133accab9ac

> Does it cause problems to set the bofereId at this point? When prefetching the styles. This callback should be called pretty much emediately?

There will be a console error, but otherwise it works, because on the next re-render the `beforeId` will be taken into account.

**Comment by Janekdererste** [comment]
> next re-render the beforeId will be taken into account.
If I understand this correctly, our layers become part of the style object once they have been added to mapbox. Would it make sense to make the path layer a part of the style which is stored in the store? Then, the layer would be 'already there' when the style is loaded and we would only have to modify the data with which the layer is rendered. 

I certainly have no idea how one would do that, I just wanted to propose in case it could be done.

**Comment by easbar** [comment]
I created a minimal example and asked for support upstream: https://github.com/visgl/react-map-gl/discussions/1541

**Comment by easbar** [comment]
Since we focus on raster tiles and will switch to OpenLayers I'll close here.

**Pull request closed without merging**
