### PR TITLE
Current location

### PR DESCRIPTION
**Pull request by karussell**
Proposal for #33

### CODE REVIEW

**Comment by Janekdererste** [comment]
I like how this works.

The way this is plugged into the geocoding results is a little hacky though I think. If I may, I would re-organize a little to make better use of typescript's type system.

**Comment by karussell** [comment]
Sure, of course, please feel free to rewrite it :)

**Comment by Janekdererste** [comment]
Okay, I've re-factored some parts. I don't understand the remaining TODO though. If you feel that this is ready to be merged go ahead please. 😀

**Comment by karussell** [comment]
Thanks!

> I don't understand the remaining TODO though. 

Will remove this. The TODO does not belong into this branch. Only for my experimental navi branch where I continuously request the location after this (initial) location request.

**Comment by Janekdererste** [comment]
> Only for my experimental navi branch where I continuously request the location after this (initial) location request.

I see. I had accidentially checked out this branch at some point and was confused how complicated the current location selection was :-)

**Pull request merged**
