### PR TITLE
allow using API key from URL

### PR DESCRIPTION
**Pull request by karussell**
Heavy users are blocked. If they have an own API key we should make it possible to let them use it via the URL parameter.
E.g. https://graphhopper.com/maps2/?key=YOUR_KEY

The changes are a bit involved as we currently create two APIImpl instances due to convenience (I think) which is now no longer possible.

Related to #118

### CODE REVIEW

**Comment by karussell** [comment]
> The changes are a bit involved

Found a simpler way and used the singleton directly where the apiImpl is used.

**Comment by Janekdererste** [comment]
If you intend to use the api as a singleton like object. We could supply the api key as constructor parameter since it will never change anyway.

**Comment by Janekdererste** [comment]
Changed api to be a real singleton. If you like it as well, you may merge the pr.

**Comment by karussell** [comment]
Thanks a lot!

**Pull request merged**
